<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ComunasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $regiones = [
            // Arica y Parinacota
            1 => [
                'Arica',
                'Camarones',
                'Putre',
                'General Lagos',
            ],

            //  Tarapacá
            2 => [
                'Iquique',
                'Alto Hospicio',
                'Pozo Almonte',
                'Camiña',
                'Colchane',
                'Huara',
                'Pica',
            ],

            //  Antofagasta
            3 => [
                'Antofagasta',
                'Mejillones',
                'Sierra Gorda',
                'Taltal',
                'Calama',
                'Ollagüe',
                'San Pedro de Atacama',
                'Tocopilla',
                'María Elena',
            ],

            //  Atacama
            4 => [
                'Copiapó',
                'Caldera',
                'Tierra Amarilla',
                'Chañaral',
                'Diego de Almagro',
                'Vallenar',
                'Alto del Carmen',
                'Freirina',
                'Huasco',
            ],

            //  Coquimbo
            5 => [
                'La Serena',
                'Coquimbo',
                'Andacollo',
                'La Higuera',
                'Paiguano',
                'Vicuña',
                'Illapel',
                'Canela',
                'Los Vilos',
                'Salamanca',
                'Ovalle',
                'Combarbalá',
                'Monte Patria',
                'Punitaqui',
                'Río Hurtado',
            ],

            //  Valparaíso
            6 => [
                'Valparaíso',
                'Casablanca',
                'Concón',
                'Juan Fernández',
                'Puchuncaví',
                'Quintero',
                'Viña del Mar',
                'Isla de Pascua',
                'Los Andes',
                'Calle Larga',
                'Rinconada',
                'San Esteban',
                'La Ligua',
                'Cabildo',
                'Papudo',
                'Petorca',
                'Zapallar',
                'Quillota',
                'La Cruz',
                'La Calera',
                'Hijuelas',
                'Nogales',
                'San Antonio',
                'Algarrobo',
                'Cartagena',
                'El Quisco',
                'El Tabo',
                'Santo Domingo',
                'San Felipe',
                'Catemu',
                'Llaillay',
                'Panquehue',
                'Putaendo',
                'Santa María',
                'Quilpué',
                'Limache',
                'Olmué',
                'Villa Alemana',
            ],
            // Metropolitana
            7 => [
                'Santiago',
                'Cerrillos',
                'Cerro Navia',
                'Conchalí',
                'El Bosque',
                'Estación Central',
                'Huechuraba',
                'Independencia',
                'La Cisterna',
                'La Florida',
                'La Granja',
                'La Pintana',
                'La Reina',
                'Las Condes',
                'Lo Barnechea',
                'Lo Espejo',
                'Lo Prado',
                'Macul',
                'Maipú',
                'Ñuñoa',
                'Pedro Aguirre Cerda',
                'Peñalolén',
                'Providencia',
                'Pudahuel',
                'Quilicura',
                'Quinta Normal',
                'Recoleta',
                'Renca',
                'San Joaquín',
                'San Miguel',
                'San Ramón',
                'Vitacura',
                'Puente Alto',
                'Pirque',
                'San José de Maipo',
                'Colina',
                'Lampa',
                'Tiltil',
                'San Bernardo',
                'Buin',
                'Calera de Tango',
                'Paine',
                'Melipilla',
                'Alhué',
                'Curacaví',
                'María Pinto',
                'San Pedro',
                'Talagante',
                'El Monte',
                'Isla de Maipo',
                'Padre Hurtado',
                'Peñaflor',
            ],
            //  Libertador Gral. Bernardo O’Higgins
            8 => [
                'Rancagua',
                'Codegua',
                'Coinco',
                'Coltauco',
                'Doñihue',
                'Graneros',
                'Las Cabras',
                'Machalí',
                'Malloa',
                'Mostazal',
                'Olivar',
                'Peumo',
                'Pichidegua',
                'Quinta de Tilcoco',
                'Rengo',
                'Requínoa',
                'San Vicente',
                'Pichilemu',
                'La Estrella',
                'Litueche',
                'Marchihue',
                'Navidad',
                'Paredones',
                'San Fernando',
                'Chépica',
                'Chimbarongo',
                'Lolol',
                'Nancagua',
                'Palmilla',
                'Peralillo',
                'Placilla',
                'Pumanque',
                'Santa Cruz',
            ],

            //  Maule
            9 => [
                'Talca',
                'Constitución',
                'Curepto',
                'Empedrado',
                'Maule',
                'Pelarco',
                'Pencahue',
                'Río Claro',
                'San Clemente',
                'San Rafael',
                'Cauquenes',
                'Chanco',
                'Pelluhue',
                'Curicó',
                'Hualañé',
                'Licantén',
                'Molina',
                'Rauco',
                'Romeral',
                'Sagrada Familia',
                'Teno',
                'Vichuquén',
                'Linares',
                'Colbún',
                'Longaví',
                'Parral',
                'Retiro',
                'San Javier',
                'Villa Alegre',
                'Yerbas Buenas',
            ],
            //Ñuble
            10 => [
                'Bulnes',
                'Chillán',
                'Chillán Viejo',
                'El Carmen',
                'Pemuco',
                'Pinto',
                'Quillón',
                'San Ignacio',
                'Yungay',
                'Coihueco',
                'Ñiquén',
                'San Carlos',
                'San Fabián',
                'San Nicolás',
                'Coelemu',
                'Ninhue',
                'Portezuelo',
                'Quirihue',
                'Ránquil',
                'Treguaco',
            ],
            //  Biobío
            11 => [
                'Concepción',
                'Coronel',
                'Chiguayante',
                'Florida',
                'Hualqui',
                'Lota',
                'Penco',
                'San Pedro de la Paz',
                'Santa Juana',
                'Talcahuano',
                'Tomé',
                'Hualpén',
                'Lebu',
                'Arauco',
                'Cañete',
                'Contulmo',
                'Curanilahue',
                'Los Álamos',
                'Tirúa',
                'Los Ángeles',
                'Antuco',
                'Cabrero',
                'Laja',
                'Mulchén',
                'Nacimiento',
                'Negrete',
                'Quilaco',
                'Quilleco',
                'San Rosendo',
                'Santa Bárbara',
                'Tucapel',
                'Yumbel',
                'Alto Biobío',
            ],

            // La Araucanía
            12 => [
                'Temuco',
                'Carahue',
                'Cunco',
                'Curarrehue',
                'Freire',
                'Galvarino',
                'Gorbea',
                'Lautaro',
                'Loncoche',
                'Melipeuco',
                'Nueva Imperial',
                'Padre Las Casas',
                'Perquenco',
                'Pitrufquén',
                'Pucón',
                'Saavedra',
                'Teodoro Schmidt',
                'Toltén',
                'Vilcún',
                'Villarrica',
                'Cholchol',
                'Angol',
                'Collipulli',
                'Curacautín',
                'Ercilla',
                'Lonquimay',
                'Los Sauces',
                'Lumaco',
                'Purén',
                'Renaico',
                'Traiguén',
                'Victoria',
            ],

            // Los Ríos
            13 => [
                'Valdivia',
                'Corral',
                'Lanco',
                'Los Lagos',
                'Máfil',
                'Mariquina',
                'Paillaco',
                'Panguipulli',
                'La Unión',
                'Futrono',
                'Lago Ranco',
                'Río Bueno',
            ],

            // Los Lagos
            14 => [
                'Puerto Montt',
                'Calbuco',
                'Cochamó',
                'Fresia',
                'Frutillar',
                'Los Muermos',
                'Llanquihue',
                'Maullín',
                'Puerto Varas',
                'Castro',
                'Ancud',
                'Chonchi',
                'Curaco de Vélez',
                'Dalcahue',
                'Puqueldón',
                'Queilén',
                'Quellón',
                'Quemchi',
                'Quinchao',
                'Osorno',
                'Puerto Octay',
                'Purranque',
                'Puyehue',
                'Río Negro',
                'San Juan de la Costa',
                'San Pablo',
                'Chaitén',
                'Futaleufú',
                'Hualaihué',
                'Palena',
            ],

            // Aysén
            15 => [
                'Coyhaique',
                'Lago Verde',
                'Aysén',
                'Cisnes',
                'Guaitecas',
                'Cochrane',
                'O\'Higgins',
                'Tortel',
                'Chile Chico',
                'Río Ibáñez',
            ],

            // Magallanes y Antártica
            16 => [
                'Punta Arenas',
                'Laguna Blanca',
                'Río Verde',
                'San Gregorio',
                'Cabo de Hornos',
                'Antártica',
                'Porvenir',
                'Primavera',
                'Timaukel',
                'Natales',
                'Torres del Paine',
            ],


        ];

        // -----------------------------------------------------------------
        // Construimos el array final [nom_comuna, id_region]
        // -----------------------------------------------------------------
        $comunas = [];

        foreach ($regiones as $idRegion => $lista) {
            foreach ($lista as $nombre) {
                $comunas[] = [
                    'nom_comuna' => $nombre,
                    'id_region'  => $idRegion,
                ];
            }
        }

        DB::table('comunas')->insert($comunas);
    }
}
